language: python

cache: pip

python:
  - "3.5"
  - "3.6"

# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: "3.7"
      dist: xenial
      sudo: true

install:
  - pip install -r requirements-test.txt

script:
  - bash test.sh --noinstall --no-update --novirtualenv --strict

after_success:
  - codecov