language: python

cache: pip

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

install:
  - pip install -r requirements-test.txt

script:
  - bash test.sh --noinstall --no-update --novirtualenv --strict

after_success:
  - codecov